# =========================
# Build Angular
# =========================
FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./

COPY apps/frontend ./apps/frontend

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/frontend

RUN pnpm build


# =========================
# Nginx Runtime
# =========================
FROM nginx:alpine

COPY apps/frontend/nginx.azure.conf /etc/nginx/templates/default.conf.template

COPY --from=builder \
/app/apps/frontend/dist/geosafe-front/browser \
/usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]