FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./

COPY apps ./apps

RUN pnpm install --frozen-lockfile

EXPOSE 4200

CMD ["pnpm", "run", "start", "--", "--host=0.0.0.0", "--poll=2000", "--disable-host-check"]