FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY apps/frontend/package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY apps/frontend ./

EXPOSE 4200

CMD ["pnpm", "start", "--host", "0.0.0.0", "--poll", "1000"]