FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./

COPY apps/backend ./apps/backend/

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/backend

EXPOSE 3333

CMD ["pnpm", "dev"]