FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY turbo.json ./

COPY apps/backend ./apps/backend/

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/backend

EXPOSE 3333

CMD ["sh", "-c", "pg_isready -h db -U root -d geosafe -t 60 && pnpm exec ace migration:run && pnpm dev"]