FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY package.json ./

COPY apps ./apps

RUN pnpm install --frozen-lockfile

EXPOSE 3333

CMD ["pnpm", "run", "dev"]