name: GeoSafe CD DEVELOP

on:
  push:
    branches:
      - develop
      - feature/deploimentTerraform

permissions:
  contents: read
  id-token: write


env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_FRONTEND: geosafe-frontend
  IMAGE_BACKEND: geosafe-backend

  RESOURCE_GROUP: rg-geosafe-dev

  FRONTEND_APP: ca-frontend-geosafe-dev
  BACKEND_APP: ca-backend-geosafe-dev

  MIGRATION_JOB: job-geosafe-migration-dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # AZURE LOGIN OIDC
      # =========================
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # =========================
      # AZURE
      # =========================
      - name: Select subscription
        run: |
          az account set \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure
        run: |
          az account show
          az group show --name rg-geosafe-dev
          az containerapp list \
            --resource-group rg-geosafe-dev \
            --output table 

      # =========================
      # ACR LOGIN
      # =========================
      - name: Login to ACR
        run: |
          az acr login \
            --name acrgeosafedev

      # =========================
      # BUILD
      # =========================
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/frontend/Dockerfile.azure
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:develop
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:dev-${{ github.run_number }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:develop
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:dev-${{ github.run_number }}
      
      # ==========================================================
      # DATABASE MIGRATION
      # ==========================================================

      - name: Start database migration
        run: |
          echo "Starting database migration..."

          az containerapp job start \
            --name ${{ env.MIGRATION_JOB }} \
            --resource-group ${{ env.RESOURCE_GROUP }}


      # ----------------------------------------------------------
      # WAIT FOR MIGRATION
      # ----------------------------------------------------------

      - name: Wait for database migration
        shell: bash
        run: |

          echo "Waiting for migration job..."

          for i in {1..30}; do

            echo "Checking migration status... ($i/30)"

            STATUS=$(az containerapp job execution list \
              --name ${{ env.MIGRATION_JOB }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --query "[0].properties.status" \
              --output tsv)

            echo "Current status: $STATUS"

            case "$STATUS" in

              Succeeded)
                echo "Database migration succeeded."
                exit 0
                ;;

              Failed)
                echo "Database migration failed."
                exit 1
                ;;

              Running|Pending|Stopped)
                echo "Migration still running..."
                ;;

              *)
                echo "Migration status not yet available..."
                ;;

            esac

            sleep 10

          done

          echo "Migration timeout."
          exit 1

      # ----------------------------------------------------------
      # DEPLOIMENT
      # ----------------------------------------------------------

      - name: Deploy Frontend
        run: |
          az containerapp update \
            --name ca-frontend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:develop

      - name: Deploy Backend
        run: |
          az containerapp update \
            --name ca-backend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:develop