name: GeoSafe CD DEV

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_FRONTEND: ${{ github.repository_owner }}/geosafe-frontend
  IMAGE_BACKEND: ${{ github.repository_owner }}/geosafe-backend

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # FRONTEND
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_FRONTEND }}:develop
            ghcr.io/${{ env.IMAGE_FRONTEND }}:dev-${{ github.run_number }}

      # BACKEND
      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:develop
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:dev-${{ github.run_number }}
      
      # ==========================================================
      # DATABASE MIGRATION
      # ==========================================================

      - name: Start database migration
        run: |
          echo "Starting database migration..."

          az containerapp job start \
            --name ${{ env.MIGRATION_JOB }} \
            --resource-group ${{ env.RESOURCE_GROUP }}


      # ----------------------------------------------------------
      # WAIT FOR MIGRATION
      # ----------------------------------------------------------

      - name: Wait for database migration
        shell: bash
        run: |

          echo "Waiting for migration job..."

          for i in {1..30}; do

            echo "Checking migration status... ($i/30)"

            STATUS=$(az containerapp job execution list \
              --name ${{ env.MIGRATION_JOB }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --query "[0].properties.status" \
              --output tsv)

            echo "Current status: $STATUS"

            case "$STATUS" in

              Succeeded)
                echo "Database migration succeeded."
                exit 0
                ;;

              Failed)
                echo "Database migration failed."
                exit 1
                ;;

              Running|Pending|Stopped)
                echo "Migration still running..."
                ;;

              *)
                echo "Migration status not yet available..."
                ;;

            esac

            sleep 10

          done

          echo "Migration timeout."
          exit 1

      # ----------------------------------------------------------
      # DEPLOIMENT
      # ----------------------------------------------------------

      - name: Deploy Frontend
        run: |
          az containerapp update \
            --name ca-frontend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:dev-${{ github.run_number }}

      - name: Deploy Backend
        run: |
          az containerapp update \
            --name ca-backend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:dev-${{ github.run_number }}
