name: GeoSafe CD DEV

on:
  push:
    branches:
      - develop
      - feature/deploimentTerraform

permissions:
  contents: read
  id-token: write


env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_FRONTEND: geosafe-frontend
  IMAGE_BACKEND: geosafe-backend


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # AZURE LOGIN OIDC
      # =========================
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # =========================
      # ACR LOGIN + SELECT SUBSCRIPTION
      # =========================
      - name: Login to ACR
        run: |
          az acr login \
            --name acrgeosafedev
      - name: Select subscription
        run: |
          az account set \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # =========================
      # FRONTEND
      # =========================
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/frontend/Dockerfile.azure
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:develop
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:dev-${{ github.run_number }}


      # =========================
      # DEPLOY FRONTEND
      # =========================
      - name: Deploy Frontend
        run: |
          az containerapp update \
            --name ca-frontend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:develop

      # =========================
      # BACKEND
      # =========================
      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:develop
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:dev-${{ github.run_number }}

      # =========================
      # DEPLOY BACKEND
      # =========================
      - name: Deploy Backend
        run: |
          az containerapp update \
            --name ca-backend-geosafe-dev \
            --resource-group rg-geosafe-dev \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:develop